### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#1]
1) Необходимо чтоб заказчик мог создать аккаунт не только через Twitch , но и через ввод Логин + е-мейла + пароль.
То есть , когда плользователь попадает на открытую страницу http://djtw.ch/@Vterka , там он нажимает кнопку "Order Music Now for 3 $"
и появляется всплывающее окно с авторизацией -  вверху поля ввода Логин + е-мейла + пароль, а внизу кнопка "Connect with Twitch"
Пользователь либо залогиниться под Твичем либо вводит емейл , логин и пароль. Если же пользователь зарегистрирован, то в форме с созданием аккаунта нужно добавить ссылку "Sign In"

2) у пользователя Junkwin стоит в настройках цена за песню $ 2 но на странице заказа отображается "// order song for $ 2.60"
Необходимо, чтоб заказчик музыки видел точно ту цену, которую указал стример (в случае оплаты с баланса)
на другом пользователе поставил цену: 3 долл , а на странице заказа отображено 4.33 долл

3) Необходимо отключить запрос на "Ключ потока", так как он не нужен, а стримеры будут боятся его давать

4) Нужна страница очереди плеера: http://djtw.ch/@Vterka  , к которой незарегистрированный пользователь нажимает "Order Music Now for 3 $".
При этом стример на этой же странице ( http://djtw.ch/@Vterka ) видит кнопку включения приема заказов.

5) насчет оплаты:  давайте сейчас сделаем так - если у юзера на балансе 0 , то на странице заказа, он будет платить не за 1 песню, допустим 3.30 долл. А ему будет даваться возможность самому пополнить баланс (минимум 5 долл и это будет описано.)

**Comment by ifrond** [comment]
pp3 pp4 готовы

**Comment by ifrond** [comment]
pp2 готово

**Comment by ifrond** [comment]
готово
