### ISSUE TITLE
Критическая ошибка

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#12]
Стример как только зарегистрировался и у него нет заказов, то плеер вообще нельзя включить

Нужно , чтоб на странице стримера https://djtw.ch/@Blozixdextr  уже сразу отображалась кнопка включения стрима  "Start my player"

![image](https://cloud.githubusercontent.com/assets/2786905/10939483/3549d904-8302-11e5-8897-e3b697067ef9.png)

**Comment by ifrond** [comment]
Готово.
Отображается кнопка Start my player для стримеров без заказов тоже
Плеер будет в режиме ожидания и ждать первого заказа. как только заказ появится, запустится соответствующий плеер
