### ISSUE TITLE
New list

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#3]
1) нужно сделать кнопку "Play this music again" - если стример протупил и не включил звук, нужно повторно принудительно запустить песню из истории

"2) заказал песню из Саунд Клауд, и нажал на ""Order"" прежде чем прогрузилась розовая полоса загрузки на фрейме саундклауда
Выбилась вот такая ошибка  https://slack-imgs.com/?url=http%3A%2F%2Fdl2.joxi.net%2Fdrive%2F0010%2F4065%2F712673%2F151020%2Fd62c3988a6.jpg&width=445&height=250  Попробовал другую песню - удалось заказать"

3) После проигрывания одной песни прошло некоторое время. Потом был заказ еще на одну песню . Она просто тупо висит в списке ожидания, но не воспроизводиться (не показывается плеер и нет звука). Страница не перезагружалась, кнопка плеера не отжималась. НО после обновления страницы и нажатия кнопки включения плеера песня стала воспроизводиться

4)Нужно также сделать эту кнопку с динамически меняющейся ценой http://joxi.ru/v29loNNS1qpwmG

5) На странице запуска плеера нужно сдеать корректное отображение баланса и по возможности его динамично менять без перезагрузки страницы, чтоб стример видел, как растет его баланс

6) на странице http://djtw.ch/@Vterka необходимо сделать обратный порядок сортировки  (самые последние заказы должны находиться сверху)

**Comment by blozixdextr** [comment]
7) Также необходимо запоминать статус нажатой кнопки "Start my stream!" - если стример обновил страницу, то нужно оставить кнопку включенной

**Comment by blozixdextr** [comment]
8) Заметил такое:  в комментариях к заказу, когда заказчик вводит текст, затем добавляет в конце перевод строки , то мы получаем на выходе символ переноса строки (<br>) . Можно его либо удалять либо что-то другое сделать

**Comment by ifrond** [comment]
pp2, pp3, pp4, pp6 готовы

**Comment by ifrond** [comment]
pp8 готово

**Comment by ifrond** [comment]
pp5 готово

**Comment by ifrond** [comment]
pp7 готово

**Comment by ifrond** [comment]
#3 pp1 готово
