### ISSUE TITLE
Показатели баланса

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#4]
Заметил:

1) На странице с плеером был показан баланс 41.60 , в то время как в биллинге баланс 46 .
Это возникает если в очереди, допустим , заказано наперед 3-4 песни

2) При воспроизведении плеера с СаундКлауда там нет регулятора громкости. Была такая ситуация - стример настроил среднюю громкость на Ютуб плеере и неожиданно запустился СаундКлауд плеер с громкостью в 2 раза больше . Есть ли возможность регулировать громкость плеера СаундКлауд ?

**Comment by ifrond** [comment]
1. у нас есть 2 вида баланса - полный баланс и баланс доступный для вывода. Для пользователя, который не стримет, а только заказывает - важен только полный баланс (доступных для заказа). Выводить внесенные суммы он не может, поэтому доступный баланс у него почти всегда равен 0.
Для стримера же важен доступный для вывода баланс и именно его я показывают на странице плеера. При заказе песен, деньги перечисляются на счет сразу же, но блокируются. Я согласен, тут есть какая-то непонятность, но как ее разрешить я не знаю. Может вы подскажете?

**Comment by ifrond** [comment]
2. у плеера soundcloud нет встроенного регулятора звука. https://www.soundcloudcommunity.com/soundcloud/topics/volume-control-nuocgr2e2nh0r?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all Я могу сделать свой регулятор с html5 slider control Примерно так http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_range под плеером.

**Comment by ifrond** [comment]
готово
