### ISSUE TITLE
Страница с баннерами

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#5]
1) Необходимо сделать страницу в меню "My banners" и папку на сервере , в которую я смогу закачать, допустим, N баннеров (PNG либо GIF-анимированные) . Если вдруг не получается наложить на анимированные GIF баннеры, то не нужно тогда их использовать.

На странице "My banners" все эти N баннеров выводятся с наложением текста:
Djtw.ch/@SomeLongAcсount , все они выводятся внизу слева с отступами от низа в 5 пикселей.
Необходимо чтоб шрифт написания был "Lato". Цвет шрифта: 001427

В данном архиве файл шрифта и примеры баннеров: http://rghost.ru/6cYh4XDkR

Вот пример баннера с уже написанным тестом 
![djtw ch- 1](https://cloud.githubusercontent.com/assets/2786905/10710524/fcf25ed0-7a66-11e5-8a06-b88cb57ec3ee.png)

Размеры баннеров могут быть от 200 на 100 px  до  400 на 200 px 

2) Также нужна кнопка "Download All Banners" которая позволит скачать все баннеры в zip архиве

**Comment by blozixdextr** [comment]
3) В меню есть пункт "Contuct Us" - нужно сделать страницу с отправкой сообщений на емейл blozixdextr@gmail.com

**Comment by blozixdextr** [comment]
4) Необходимо чтоб стример, после залогинивания попадал на страницу http://djtw.ch/@Blozixdextr . То есть страница включения плеера для стримера - главная и он на неё попадает сразу после регистрации.

А в меню нужно добавить ссылку на страницу "Timeline" http://djtw.ch/user/twitcher  , где стрмер сможет увидеть список всех событий.

**Comment by blozixdextr** [comment]
5) Можно немного переделать регистрацию ?
Когда покупатель песен не залогинен , то на странице http://djtw.ch/@Vterka нужно добавить кнопку "Login with Twitch account" , чтоб он мог прикрепить аккаунт твича как покупатель песен. Мы берем оттуда емейл и ставим статус юзера - покупатель песен.

**Comment by ifrond** [comment]
http://djtw.ch/user/twitcher/banners баннеры готовы

**Comment by ifrond** [comment]
готово
