### ISSUE TITLE
Можно заменить отсутствие картинки 

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#6]
Можно заменить отсутствие картинки какой-то определенной картинкой с надписью "No image"

![image](https://cloud.githubusercontent.com/assets/2786905/10744663/f8d42a78-7c3b-11e5-90b9-04cd7668bb70.png)

**Comment by ifrond** [comment]
здесь картинка по умолчанию html/assets/app/img/music-default.png
можете заменить ее на более подходящую
