### ISSUE TITLE
Нашли такой баг

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#7]
Перейдя по  адресу любого стримера http://joxi.ru/KAx9NjjHz5b1r8 , нажав на кнопку заказа песни появляется окно авторизации http://joxi.ru/VrwlNMMSlekWmX
Авторизовавшись совершается переход на эту страницу http://joxi.ru/n2Y5vOOILzyP26
Но! Если вернуться на страницу назад, то будучи уже авторизованным и нажав на эту кнопку снова http://joxi.ru/p277vooclzDZ27
Появляется всплывающее окно с таким содержимым http://joxi.ru/MAjlZppS6Q8Gme

**Comment by ifrond** [comment]
готово
