### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/djtw#9]
0) Вопрос: в какую папку можно заливать картинки на сервере, чтоб они не конфликтовали с гит ?

1) небольшое изменение в генерации баннера:  чтоб текст выводился не с левого края внизу, а всё так же внизу, но строго по центру баннера

2) удалить подключение футера для страницы плеера 
![image](https://cloud.githubusercontent.com/assets/2786905/10856468/3fca4dcc-7f48-11e5-8ad8-a42fd0661568.png)

3) Также необходимо вставить и обработать корректные значения года и месяца
![image](https://cloud.githubusercontent.com/assets/2786905/10862785/65a0b206-7fb7-11e5-8fa3-bffd53ec1a36.png)

3.1) То же самое на странице  http://prntscr.com/8xez48 . Также в модальном окне оплаты необходимо чтоб на вкладке пейпала отображалась картинка пейпала, а на странице ввода карточки отображалась другая картинка (которую мы сможем заменить)

4) Нужно определить, включен ли наш плеер у стримера и отобразить это на странице https://djtw.ch/@Blozixdextr  выше кнопки "Order next song for $2.00" в виде фраз  "Streamer`s player is online" или "Streamer`s player is offline"

5) Нужно модулю пагинации дать класс col-xs-12 ,  потому что вот такое безобразие обнаружилосЬ
http://joxi.ru/YmEDGNNS4ngLr6
Я бы и сам дал, но категорически не могу найти, наверное оно как то по особенному выводится

**Comment by blozixdextr** [comment]
![list_banners](https://cloud.githubusercontent.com/assets/2786905/10857823/a4eb4a3c-7f50-11e5-9171-c0e0fff627e0.png)

**Comment by ifrond** [comment]
0. я нашел 2 пустые папки в assets и добавил их в gitignore
/var/www/html/assets/app/upload/b
/var/www/html/assets/app/upload/t
все файлы в них будут игнорироваться git'ом
По аналогии можете добавить в игнор и другие папки, см тут  https://github.com/ifrond/djtw/blob/master/html/assets/app/upload/.gitignore

**Comment by ifrond** [comment]
3) я вижу вы скрыли форму для пополнения баланса стримера. Если вы сделали это специально, то нужно не скрывать ее, а удалить и удалить серверную часть (хотя бы роутинг)

**Comment by ifrond** [comment]
4) Нужно определить, включен ли наш плеер у стримера и отобразить это на странице https://djtw.ch/@Blozixdextr выше кнопки "Order next song for $2.00" в виде фраз "Streamers player is online" или "Streamers player is offline"
--
Мы можем раз в минуту, если играет плеер отсылать сообщение на сервер и запоминать время. А на странице стримера проверять время последней активности плеера и если разница меньше 2х минут, то считать, что плеер рабочий.
для большей точности можно делать проверку раз в 20-30 секунд
Если вы имеете в виду под онлайн, что стример либо играет что-то, либо ждет заказов, то можно записывать время каждые 20 секунд, которые мы запрашиваем очередь - это будет гораздо проще.
Скажите, пожалуйста, что именно нам нужно

**Comment by ifrond** [comment]
все кроме pp4 готово
скажите, пожалуйста, какой вариант вы выбрали
